PACKAGE=	tests
.PATH: ${SRCTOP}/tests/sys/exterr

TESTS_SUBDIRS+=        kld

TESTSDIR=	${TESTSBASE}/sys/exterr

ATF_TESTS_C+=	exterr_test
TEST_METADATA+=	required_user="root"

.include <bsd.test.mk>
